# /etc/dnsmasq.d/msg-allow.conf

# WhatsApp
# Text, no media
nftset=/g.whatsapp.net/e1.whatsapp.net/e2.whatsapp.net/e3.whatsapp.net/e4.whatsapp.net/e5.whatsapp.net/e6.whatsapp.net/e7.whatsapp.net/e8.whatsapp.net/e9.whatsapp.net/e10.whatsapp.net/e11.whatsapp.net/e12.whatsapp.net/e13.whatsapp.net/e14.whatsapp.net/e15.whatsapp.net/e16.whatsapp.net/4#inet#fw4#msg_okay
# Registration/activation
nftset=/v.whatsapp.net/dit.whatsapp.net/4#inet#fw4#msg_okay

# iMessage
# Text, no media
nftset=/push.apple.com/4#inet#fw4#msg_okay
# No Private Relay
address=/mask.icloud.com/
address=/mask-h2.icloud.com/
address=/mask-api.icloud.com/

# Signal
# Text, no media
nftset=/chat.signal.org/4#inet#fw4#msg_okay
# Registration/provisioning only
nftset=/cdsi.signal.org/svr2.signal.org/ud-chat.signal.org/4#inet#fw4#msg_okay

# Google RCS
# Text, no media
nftset=/jibe.google.com/instantmessaging-pa.googleapis.com/4#inet#fw4#msg_okay
nftset=/mtalk.google.com/mtalk4.google.com/android.googleapis.com/4#inet#fw4#msg_okay

# Facebook Messenger
nftset=/edge-mqtt.facebook.com/mqtt-mini.facebook.com/4#inet#fw4#msg_okay

# Captive portal check
nftset=/captive.apple.com/captive.g.aaplimg.com/4#inet#fw4#captive_okay
nftset=/connectivitycheck.gstatic.com/connectivitycheck.android.com/4#inet#fw4#captive_okay
