#!/bin/sh

# Clean away any old rules
nft -a list chain inet fw4 forward_lan 2>/dev/null | grep 'comment "allow-msgs"' | sed 's/.*# handle //' \
	| while read -r h; do
		nft delete rule inet fw4 forward_lan handle "$h"
	done
nft -a list chain inet fw4 dstnat 2>/dev/null | grep 'comment "allow-msgs"' | sed 's/.*# handle //' \
	| while read -r h; do
		nft delete rule inet fw4 dstnat handle "$h"
	done

#
# Pools of IP addresses managed by dnsmasq
#
nft add set inet fw4 msg_okay '{ type ipv4_addr; flags interval, timeout; timeout 6h; }' 2>/dev/null

#
# Use the tables created above to selectively allow traffic to just the text services we support.
# Everything is throttled regardless, which is fine for small text but will kill larger data if it gets through.
# Everything else will be dropped.
#
nft insert rule inet fw4 forward_lan                                                   counter drop               comment '"allow-msgs"'
nft insert rule inet fw4 forward_lan ip daddr @msg_okay tcp dport 443                  counter accept             comment '"allow-msgs"'
nft insert rule inet fw4 forward_lan ip daddr @msg_okay tcp dport 443 meter throttle443 '{ ip saddr limit rate over 4 kbytes/second }' counter drop comment '"allow-msgs"'

#
# DNS hijack
#
DNS_IP=$(uci -q get network.lan.ipaddr)
nft insert rule inet fw4 dstnat      iifname "br-lan" ip daddr != $DNS_IP udp dport 53 counter dnat ip to $DNS_IP comment '"allow-msgs"'
nft insert rule inet fw4 dstnat      iifname "br-lan" ip daddr != $DNS_IP tcp dport 53 counter dnat ip to $DNS_IP comment '"allow-msgs"'
nft insert rule inet fw4 forward_lan tcp dport 853                                     counter drop               comment '"allow-msgs"'
