#!/bin/sh

LAN_IP=$(uci -q get network.lan.ipaddr)

# Clean away any old rule hooks
nft -a list chain inet fw4 forward 2>/dev/null | grep 'comment "allow-msgs"' | sed 's/.*# handle //' \
	| while read -r h; do
		nft delete rule inet fw4 forward handle "$h"
	done
nft -a list chain inet fw4 dstnat 2>/dev/null | grep 'comment "allow-msgs"' | sed 's/.*# handle //' \
	| while read -r h; do
		nft delete rule inet fw4 dstnat handle "$h"
	done

#
# Selectively allow traffic to just the text services we support.
# Everything is throttled regardless, which is fine for small text but will kill larger data if it gets through.
# We need a modest sized burst so let the TLS handshake happen successfully.
# Everything else will be dropped.
#
nft -f - <<__EOF__
#
# This is a dummy we need because the first time these wont exist and so the flush/delete
# rules would fail, which makes this whole thing fail.
#
table inet fw4 {
	chain msg_out {
	}
	chain msg_in {
	}
	set msg_throttle {
		type ipv4_addr . ipv4_addr . inet_service . inet_service
		flags dynamic, timeout
		timeout 5m
		size 65535
	}
}

#
# Clean away the old
#
flush chain inet fw4 msg_out
flush chain inet fw4 msg_in
flush set inet fw4 msg_throttle
delete chain inet fw4 msg_out
delete chain inet fw4 msg_in
delete set inet fw4 msg_throttle

#
# Setup the new filters
#
table inet fw4 {
	set captive_okay {
		type ipv4_addr
		flags timeout
		timeout 6h
	}
	set msg_whatsapp {
		type ipv4_addr
		flags timeout
		timeout 6h
	}
	set msg_imessage {
		type ipv4_addr
		flags timeout
		timeout 6h
	}
	set msg_signal {
		type ipv4_addr
		flags timeout
		timeout 6h
	}
	set msg_googlercs {
		type ipv4_addr
		flags timeout
		timeout 6h
	}
	set msg_facebookmsg {
		type ipv4_addr
		flags timeout
		timeout 6h
	}
	set msg_slack {
		type ipv4_addr
		flags timeout
		timeout 6h
	}
	set msg_discord {
		type ipv4_addr
		flags timeout
		timeout 6h
	}
	set msg_telegram {
		type ipv4_addr
		flags interval
		elements = {
			91.108.56.0/22,
			91.108.4.0/22,
			91.108.8.0/22,
			91.108.16.0/22,
			91.108.12.0/22,
			149.154.160.0/20,
			91.105.192.0/23,
			91.108.20.0/22,
			185.76.151.0/24
		}
	}
	set msg_throttle {
		type ipv4_addr . ipv4_addr . inet_service . inet_service
		flags dynamic, timeout
		timeout 5m
		size 65535
	}
	chain msg_out {
		ct state related icmp type { destination-unreachable, time-exceeded } counter accept
		ip daddr @captive_okay tcp dport { 80, 443 } update @msg_throttle { ip daddr . ip saddr . tcp dport . tcp sport limit rate over 1 kbytes/second burst 32 kbytes } counter drop
		ip daddr @captive_okay tcp dport { 80, 443 } counter accept
		ip daddr @msg_whatsapp tcp dport 443 update @msg_throttle { ip daddr . ip saddr . tcp dport . tcp sport limit rate over 1 kbytes/second burst 32 kbytes } counter drop
		ip daddr @msg_whatsapp tcp dport 443 counter accept
		ip daddr @msg_imessage tcp dport 443 update @msg_throttle { ip daddr . ip saddr . tcp dport . tcp sport limit rate over 1 kbytes/second burst 128 kbytes } counter drop
		ip daddr @msg_imessage tcp dport 443 counter accept
		ip daddr @msg_signal tcp dport 443 update @msg_throttle { ip daddr . ip saddr . tcp dport . tcp sport limit rate over 1 kbytes/second burst 32 kbytes } counter drop
		ip daddr @msg_signal tcp dport 443 counter accept
		ip daddr @msg_googlercs tcp dport 443 update @msg_throttle { ip daddr . ip saddr . tcp dport . tcp sport limit rate over 1 kbytes/second burst 32 kbytes } counter drop
		ip daddr @msg_googlercs tcp dport 443 counter accept
		ip daddr @msg_facebookmsg tcp dport 443 update @msg_throttle { ip daddr . ip saddr . tcp dport . tcp sport limit rate over 1 kbytes/second burst 32 kbytes } counter drop
		ip daddr @msg_facebookmsg tcp dport 443 counter accept
		ip daddr @msg_slack tcp dport 443 update @msg_throttle { ip daddr . ip saddr . tcp dport . tcp sport limit rate over 1 kbytes/second burst 32 kbytes } counter drop
		ip daddr @msg_slack tcp dport 443 counter accept
		ip daddr @msg_discord tcp dport 443 update @msg_throttle { ip daddr . ip saddr . tcp dport . tcp sport limit rate over 1 kbytes/second burst 32 kbytes } counter drop
		ip daddr @msg_discord tcp dport 443 counter accept
		ip daddr @msg_telegram tcp dport 443 update @msg_throttle { ip daddr . ip saddr . tcp dport . tcp sport limit rate over 1 kbytes/second burst 32 kbytes } counter drop
		ip daddr @msg_telegram tcp dport 443 counter accept
		meta l4proto tcp counter reject with tcp reset
		counter reject
	}
	chain msg_in {
		ct state related icmp type { destination-unreachable, time-exceeded } counter accept
		ct state established update @msg_throttle { ip saddr . ip daddr . tcp sport . tcp dport } counter drop
		ct state established counter accept
		meta l4proto tcp counter reject with tcp reset
		counter reject
	}
}

#
# Hook our filter rules into the forward chain
#
insert rule inet fw4 forward iifname "br-lan" counter jump msg_out comment "allow-msgs"
insert rule inet fw4 forward oifname "br-lan" counter jump msg_in comment "allow-msgs"

#
# Add a DNS hijack hook
#
insert rule inet fw4 dstnat iifname "br-lan" ip daddr != $LAN_IP udp dport 53 counter dnat ip to $LAN_IP comment "allow-msgs"
insert rule inet fw4 dstnat iifname "br-lan" ip daddr != $LAN_IP tcp dport 53 counter dnat ip to $LAN_IP comment "allow-msgs"

#
# Add a NTP hijack hook
#
insert rule inet fw4 dstnat iifname "br-lan" ip daddr != $LAN_IP udp dport 123 counter dnat ip to $LAN_IP comment "allow-msgs"

__EOF__
